name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: Build the application
        run: cargo build --release --target x86_64-pc-windows-msvc
        shell: bash

      - name: Rename executable
        run: mv target/x86_64-pc-windows-msvc/release/librarylink.exe librarylink.exe
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: librarylink.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
